GET https://petshelter2020.herokuapp.com/pets/
###
GET https://petshelter2020.herokuapp.com/pets/1
###
GET https://petshelter2020.herokuapp.com/pets/search?type=dog&age=1&gender=girl
###
POST https://petshelter2020.herokuapp.com/pets/save
Content-Type: application/json

{
  "name": "Busya",
  "type": "kat",
  "age": 1,
  "gender": "girl",
 "shelterId": 3
}
###
DELETE https://petshelter2020.herokuapp.com/pets/remove/
###
POST https://petshelter2020.herokuapp.com/pets/update/
Content-Type: application/json

{
  "id": 2,
  "name": "Bobik",
  "shelterId": 1
}


###